version: '3'

services:
    run_lowprice_serveur:
        user: "1000:1000"
        build:
            context: .
            args:
                DOCKER_GATEWAY_HOST: ${DOCKER_GATEWAY_HOST:-host.docker.internal}
        volumes:
            - ./:/var/www/html
        environment:
            APACHE_DOCUMENT_ROOT: /var/www/html/public
            XDEBUG_CONFIG: remote_host=${DOCKER_GATEWAY_HOST:-host.docker.internal}

        restart: on-failure
        ports:
            - "8083:80"

    db_lowprice:
        image: mariadb:10.3
        environment:
        - MYSQL_ROOT_PASSWORD=secret
        - MYSQL_DATABASE=app
        - MYSQL_USER=root
        - MYSQL_PASSWORD=secret
        command: mysqld --general-log=1 --default-authentication-plugin=mysql_native_password --general-log-file=/var/log/mysql/general-log.log
        restart: on-failure
        ports:
        - "9908:3306"
