- name: Low Price Post
  hosts: saas_low_price_post
  user: ubuntu
  become: true
  become_user: root

  roles:
#    - roles/system/base
    - roles/app/git
#    - roles/system/apache
#    - roles/system/phpfpm
    - role: roles/app/php
      become: yes
      become_user: www-data
